 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/developers", type: :request do
  
  # Developer. As you add validations to Developer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Developer.create! valid_attributes
      get developers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      developer = Developer.create! valid_attributes
      get developer_url(developer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_developer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      developer = Developer.create! valid_attributes
      get edit_developer_url(developer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Developer" do
        expect {
          post developers_url, params: { developer: valid_attributes }
        }.to change(Developer, :count).by(1)
      end

      it "redirects to the created developer" do
        post developers_url, params: { developer: valid_attributes }
        expect(response).to redirect_to(developer_url(Developer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Developer" do
        expect {
          post developers_url, params: { developer: invalid_attributes }
        }.to change(Developer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post developers_url, params: { developer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested developer" do
        developer = Developer.create! valid_attributes
        patch developer_url(developer), params: { developer: new_attributes }
        developer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the developer" do
        developer = Developer.create! valid_attributes
        patch developer_url(developer), params: { developer: new_attributes }
        developer.reload
        expect(response).to redirect_to(developer_url(developer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        developer = Developer.create! valid_attributes
        patch developer_url(developer), params: { developer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested developer" do
      developer = Developer.create! valid_attributes
      expect {
        delete developer_url(developer)
      }.to change(Developer, :count).by(-1)
    end

    it "redirects to the developers list" do
      developer = Developer.create! valid_attributes
      delete developer_url(developer)
      expect(response).to redirect_to(developers_url)
    end
  end
end
